<main class='container ml-page'>
    <section>
        <h1>Mentions Légales</h1>
        
        <article>
            <h2>1. Présentation du site internet</h2>
            <p>
                En vertu de l'article 6 de la loi n° 2004-575 du 21 juin 2004 pour la confiance dans l'économie numérique, 
                il est précisé aux utilisateurs du site internet https://trainWithMe.fr
                l'identité des différents intervenants dans le cadre de sa réalisation et de son suivi:
            </p>
            <p><span>Propriétaire :</span> CHARLES SAVANNAH – 19 ALLEE PAUL ELUARD 95100 ARGENTEUIL</p>
            <p><span>Responsable publication personne physique :</span> Savannah CHARLES – charles.savannah0@gmail.com</p>
            <p><span>Webmaster :https://trainwithme.fr</span> – charles.savannah0@gmail.com</p>
            <p><span>Hébergeur :</span> 3wa – 46 Rue René Clair, 75018 Paris 75018 PARIS 01 75 43 42 42</p>
            <p><span>Délégué à la protection des données :</span> <b>CHARLES Savannah</b> – charles.savannah0@gmail.com</p>
        </article>
        
        <article>
            <h2>2. Conditions générales d’utilisation du site et des services proposés.</h2>
            <p>
                Le Site constitue une œuvre de l’esprit protégée par les dispositions du Code de la Propriété Intellectuelle et des Réglementations Internationales applicables. 
                Le Client ne peut en aucune manière réutiliser, céder ou exploiter pour son propre compte tout ou partie des éléments ou travaux du Site.
            </p>
            <p>
                L’utilisation du site https://trainwithme.fr implique l’acceptation pleine et entière des conditions générales d’utilisation ci-après décrites. 
                Ces conditions d’utilisation sont susceptibles d’être modifiées ou complétées à tout moment, 
                les utilisateurs du site https://trainwithme.fr sont donc invités à les consulter de manière régulière.
            </p>
            <p>
                Ce site internet est normalement accessible à tout moment aux utilisateurs. Une interruption pour raison de maintenance technique peut être toutefois décidée par https://trainwithme.fr, 
                qui s’efforcera alors de communiquer préalablement aux utilisateurs les dates et heures de l’intervention. Le site web https://trainwithme.fr  est mis à jour régulièrement par <b>Savannah CHARLES</b> responsable. 
                De la même façon, les mentions légales peuvent être modifiées à tout moment : elles s’imposent néanmoins à l’utilisateur qui est invité à s’y référer le plus souvent possible afin d’en prendre connaissance.
            </p>
        </article>
        <article>
            <h2>3. Description des services fournis</h2>
            <p>
                Le Service comprend l’ensemble des fonctionnalités, des applications, des services, et des technologies que nous vous fournissons afin, de
                vous donner l'opportunité personnalisée de communiquer et établir des liens avec d'autres utilisateurs.
            </p>
        </article>
        <article>
            <h2>4. Limitations contractuelles sur les données techniques.</h2>
            <p>
                Le site utilise la technologie JavaScript. Le site Internet ne pourra être tenu responsable de dommages matériels liés à l’utilisation du site. 
                De plus, l’utilisateur du site s’engage à accéder au site en utilisant un matériel récent, ne contenant pas de virus et avec un navigateur de dernière génération mis-à-jour
                Le site https://trainwithme.fr est hébergé chez un prestataire sur le territoire de l’Union Européenne conformément aux dispositions du Règlement Général sur la Protection des Données (RGPD : n° 2016-679)
            </p>
            <p>
                L’objectif est d’apporter une prestation qui assure le meilleur taux d’accessibilité. L’hébergeur assure la continuité de son service 24 Heures sur 24, tous les jours de l’année. 
                Il se réserve néanmoins la possibilité d’interrompre le service d’hébergement pour les durées les plus courtes possibles notamment à des fins de maintenance, d’amélioration de ses infrastructures, 
                de défaillance de ses infrastructures ou si les Prestations et Services génèrent un trafic réputé anormal.
            </p>
            <p>
                <b>Savannah CHARLES</b> et l’hébergeur ne pourront être tenus responsables en cas de dysfonctionnement du réseau Internet, 
                des lignes téléphoniques ou du matériel informatique et de téléphonie lié notamment à l’encombrement du réseau empêchant l’accès au serveur.
            </p>
        </article>
        <article>
            <h2>5. Propriété intellectuelle et contrefaçons</h2>
            <p>
                <b>Savannah CHARLES</b> est propriétaire des droits de propriété intellectuelle et détient les droits d’usage sur tous les éléments accessibles sur le site internet, 
                notamment les textes, images, graphismes, logos, vidéos, icônes et sons. Toute reproduction, représentation, modification, publication, 
                adaptation de tout ou partie des éléments du site, quel que soit le moyen ou le procédé utilisé, est interdite, sauf autorisation écrite préalable de <span>Savannah CHARLES</span>
            </p>
            <p>
                Toute exploitation non autorisée du site ou de l’un quelconque des éléments qu’il contient sera considérée comme constitutive d’une contrefaçon et poursuivie conformément aux dispositions des articles L.335-2 et suivants du Code de Propriété Intellectuelle.
            </p>
        </article>
        <article>
            <h2>6. Limitations de responsabilité</h2>
            <p>
                <b>Savannah CHARLES</b> agit en tant qu’éditeur du site.https://trainwithme.fr est responsable de la qualité et de la véracité du Contenu qu’il publie.
            </p>
            <p>
                <b>Savannah CHARLES</b> ne pourra être tenu responsable des dommages directs et indirects causés au matériel de l’utilisateur, lors de l’accès au site internet https://trainwithme.fr, 
                et résultant soit de l’utilisation d’un matériel ne répondant pas aux spécifications indiquées au point 4, soit de l’apparition d’un bug ou d’une incompatibilité.
            </p>
            <p>
                <b>Savannah CHARLES</b> ne pourra également être tenu responsable des dommages indirects (tels par exemple qu’une perte de marché ou perte d’une chance) consécutifs à l’utilisation du site https://trainwithme.fr. 
                Des espaces interactifs (possibilité de poser des questions dans l’espace contact) sont à la disposition des utilisateurs. <span>Savannah CHARLES</span> se réserve le droit de supprimer, 
                sans mise en demeure préalable, tout contenu déposé dans cet espace qui contreviendrait à la législation applicable en France, en particulier aux dispositions relatives à la protection des données. 
                Le cas échéant, https://trainwithme.fr se réserve également la possibilité de mettre en cause la responsabilité civile et/ou pénale de l’utilisateur, notamment en cas de message à caractère raciste, injurieux, diffamant, ou pornographique, 
                quel que soit le support utilisé (texte, photographie …).
            </p>
        </article>
        <article>
            <h2>7. Gestion des données personnelles</h2>
            <p>
                Le Client est informé des réglementations concernant la communication marketing, la loi du 21 Juin 2014 pour la confiance dans l’Economie Numérique, 
                la Loi Informatique et Liberté du 06 Août 2004 ainsi que du Règlement Général sur la Protection des Données (RGPD : n° 2016-679).
            </p>
            
            <h3>a - Responsables de la collecte des données personnelles</h3>
            <p>
                Pour les Données Personnelles collectées dans le cadre de la création du compte personnel de l’Utilisateur et de sa navigation sur le Site, 
                le responsable du traitement des Données Personnelles est : <span>Savannah CHARLES</span>. https://savannahcharles.sites.com est représenté par <b>Savannah CHARLES</b>, son représentant légal
            </p>
            <p>
                En tant que responsable du traitement des données qu’il collecte,https://trainwithme.fr s’engage à respecter le cadre des dispositions légales en vigueur. 
                Il lui appartient notamment au Client d’établir les finalités de ses traitements de données, de fournir à ses prospects et clients, 
                à partir de la collecte de leurs consentements, une information complète sur le traitement de leurs données personnelles et de maintenir un registre des traitements conforme à la réalité. 
                Chaque fois que https://trainwithme.fr traite des Données Personnelles, <span>Savannah CHARLES</span>
                prend toutes les mesures raisonnables pour s’assurer de l’exactitude et de la pertinence des Données Personnelles au regard des finalités pour les quelles https://trainwithme.fr les traite.
            </p>
            
            <h3>b - Finalité des données collectées</h3>
            <p>https://savannahcharles.sites.com est susceptible de traiter tout ou partie des données :</p>
            <ul>
                <li>Pour permettre la navigation sur le Site et la gestion et la traçabilité des prestations et services commandés par l’utilisateur : données de connexion et d’utilisation du Site, facturation, historique des commandes, etc.</li>
                <li>Pour prévenir et lutter contre la fraude informatique (spamming, hacking…) : matériel informatique utilisé pour la navigation, l’adresse IP, le mot de passe (hashé)</li>
                <li>Pour améliorer la navigation sur le Site : données de connexion et d’utilisation</li>
                <li>Pour mener des enquêtes de satisfaction facultatives sur https://savannahcharles.sites.com : adresse email </li>
                <li>Pour mener des campagnes de communication (sms, mail) : numéro de téléphone, adresse email</li>
            </ul>
            
            <p>TrainWithMe ne commercialise pas vos données personnelles qui sont donc uniquement utilisées par nécessité ou à des fins statistiques et d’analyses.</p>
            
            <h3>c - Droit d’accès, de rectification et d’opposition</h3>
            <p>Conformément à la réglementation européenne en vigueur, les Utilisateurs de https://trainwithme.fr disposent des droits suivants :</p>
            <ul>
                <li>
                    Droit d'accès (article 15 RGPD) et de rectification (article 16 RGPD), de mise à jour, 
                    de complétude des données des Utilisateurs droit de verrouillage ou d’effacement des données des Utilisateurs à caractère personnel (article 17 du RGPD), lorsqu’elle
                    s sont inexactes, incomplètes, équivoques, périmées, ou dont la collecte, l'utilisation, la communication ou la conservation est interdite
                </li>
                <li>droit de retirer à tout moment un consentement (article 13-2c RGPD)</li>
                <li>droit à la limitation du traitement des données des Utilisateurs (article 18 RGPD)</li>
                <li>droit d’opposition au traitement des données des Utilisateurs (article 21 RGPD)</li>
                <li>droit à la portabilité des données que les Utilisateurs auront fournies, lorsque ces données font l’objet de traitements automatisés fondés sur leur consentement ou sur un contrat (article 20 RGPD)</li>
                <li>droit de définir le sort des données des Utilisateurs après leur mort et de choisir à qui https://savannahcharles.sites.com devra communiquer (ou non) ses données à un tiers qu’ils aura préalablement désigné</li>
            </ul>
            <p>
                Dès que https://trainwithme.fr a connaissance du décès d’un Utilisateur et à défaut d’instructions de sa part, https://trainwithme.fr s’engage à détruire ses données, 
                sauf si leur conservation s’avère nécessaire à des fins probatoires ou pour répondre à une obligation légale.
            </p>
            <p>Si l’Utilisateur souhaite savoir comment https://trainwithme.fr utilise ses Données Personnelles, demander à les rectifier ou s’oppose à leur traitement, l’Utilisateur peut contacter <span>Savannah CHARLES</span> par écrit à l’adresse suivante :</p>
            <address>
                CHARLES SAVANNAH – DPO, CHARLES
                19 ALLEE PAUL ELUARD 95100 ARGENTEUIL.
            </address>
            <p>Dans ce cas, l’Utilisateur doit indiquer les Données Personnelles qu’il souhaiterait que https://trainwithme.fr corrige, mette à jour ou supprime, en s’identifiant précisément avec une copie d’une pièce d’identité (carte d’identité ou passeport).</p>
            <p>
                Les demandes de suppression de Données Personnelles seront soumises aux obligations qui sont imposées à https://trainwithme.fr par la loi, notamment en matière de conservation ou d’archivage des documents. 
                Enfin, les Utilisateurs de https://trainwithme.fr peuvent déposer une réclamation auprès des autorités de contrôle, et notamment de la CNIL (https://www.cnil.fr/fr/plaintes).
            </p>
            
            <h3>d - Non-communication des données personnelles</h3>
            <p>
                https://trainwithme.fr s’interdit de traiter, héberger ou transférer les Informations collectées sur ses Clients vers un pays situé en dehors de l’Union européenne ou reconnu comme « non adéquat » par la Commission européenne sans en informer préalablement le client. 
                Pour autant, https://trainwithme.fr reste libre du choix de ses sous-traitants techniques et commerciaux à la condition qu’il présentent les garanties suffisantes au regard des exigences du Règlement Général sur la Protection des Données (RGPD : n° 2016-679).
            </p>
            <p>
                https://trainwithme.fr s’engage à prendre toutes les précautions nécessaires afin de préserver la sécurité des Informations et notamment qu’elles ne soient pas communiquées à des personnes non autorisées. 
                Cependant, si un incident impactant l’intégrité ou la confidentialité des Informations du Client est portée à la connaissance de https://trainwithme.fr, celle-ci devra dans les meilleurs délais informer le Client et lui communiquer les mesures de corrections prises. 
                Par ailleurs https://trainwithme.fr ne collecte aucune « données sensibles ».
            </p>
            <p>
                Les Données Personnelles de l’Utilisateur peuvent être traitées par des filiales de https://trainwithme.fr et des sous-traitants (prestataires de services), 
                exclusivement afin de réaliser les finalités de la présente politique.
            </p>
            <p>
                Dans la limite de leurs attributions respectives et pour les finalités rappelées ci-dessus, les principales personnes susceptibles d’avoir accès aux données des Utilisateurs de https://trainwithme.fr sont principalement les agents de notre service client.
            </p>
        </article>
        
        <article>
            <h2>8. Notification d’incident</h2>
            <p>
                Quels que soient les efforts fournis, aucune méthode de transmission sur Internet et aucune méthode de stockage électronique n'est complètement sûre. 
                Nous ne pouvons en conséquence pas garantir une sécurité absolue. Si nous prenions connaissance d'une brèche de la sécurité, nous avertirions les utilisateurs concernés afin qu'ils puissent prendre les mesures appropriées. 
                Nos procédures de notification d’incident tiennent compte de nos obligations légales, qu'elles se situent au niveau national ou européen. 
                Nous nous engageons à informer pleinement nos clients de toutes les questions relevant de la sécurité de leur compte et à leur fournir toutes les informations nécessaires pour les aider à respecter leurs propres obligations réglementaires en matière de reporting.
            </p>
            <p>
                Aucune information personnelle de l'utilisateur du site https://trainwithme.fr n'est publiée à l'insu de l'utilisateur, échangée, transférée, cédée ou vendue sur un support quelconque à des tiers. 
                Seule l'hypothèse du rachat de https://trainwithme.fr et de ses droits permettrait la transmission des dites informations à l'éventuel acquéreur qui serait à son tour tenu de la même obligation de conservation et de modification des données vis à vis de l'utilisateur du site https://trainwithme.fr.
            </p>
        </article>
        <article>
            <h2>9. Droit applicable et attribution de juridiction.</h2>
            <p>
                Tout litige en relation avec l’utilisation du site https://trainwithme.fr est soumis au droit français. En dehors des cas où la loi ne le permet pas, il est fait attribution exclusive de juridiction aux tribunaux compétents de Argenteuil.
            </p>
        </article>
        
    </section>
</main>

