<main class="container admin-page">
    
    <!--link to admin page-->
    <a href='index.php?template=admin' class="lien-admin">Retour à la page principale</a>
    
    <h2 class='new-admin'>Nouvel Administrateur</h2>
    
    <!--------- Form to create a new user with the statut Admin ----------
    --------------------------------------------------------------------->
    <form class="form-newadmin" method="POST" action="index.php" >
        <input type="hidden" name="action" value="new-user">
        <div>
            <label for="user_name" aria-labelledby='pseudo'>Pseudo</label>
            <input type="text" id="user_name" data-type="user_name" name="user_name" minlength="7" required>
        </div>
        <div>
            <label for="last_name" aria-labelledby='nom'>Nom</label>
            <input type="text" id="last_name" data-type="last_name" name="last_name" required> 
        </div>
        <div>
            <label for="first_name" aria-labelledby='prenom'>Prenom</label>
            <input type="text" id="first_name" data-type="first_name" name="first_name" required>
        </div>
        <div>
            <label for="email" aria-labelledby='email'>Email <i class="far fa-envelope"></i></label>
            <input type="email" id="email" data-type="email" name="email" required>
        </div>
        <div>
            <label for="password" aria-labelledby='mot de passe'>Password <i class="fas fa-unlock-alt"></i></label>
            <input type="password" id="password" data-type="password" name="password" minlength="8" required>
        </div>
        <div class="div-radio">
            <label for="admin" aria-labelledby='Administrateur'>Administrateur</label>
            <input type="checkbox" id="admin" data-type="admin" value="1" name="admin" checked>
        </div>
        <div class="divbutton">
            <button type="submit" class="button-submit">Valider</button>
        </div>
    </form>
</main>